# config/config.yaml
defaults:

  - data: cb1 # デフォルトで使用するデータセット (cb1 or cb2)

  - _self_


# ハイパーパラメータの設定
hyper_params:

  # 刻み幅
  dt: 0.0002 # 1/5000 s

  # Linear Filterのパラメータ
  J: 15
  tau: 30

  # 初期初期占有率設定
  R_start: 0.842
  A_start: 0.157
  I1_start: 0.001
  I2_start: 0.000

  # パラメータの定義域
  param_bounds:
    LinearFilter:
      alphas: [-5.0, 5.0]  ## alphas (L1-L15): 論文に制約なし。
      delta: [0.0, 0.002] #  delta: 論文で (0.0, 0.002) 秒 (0-2ms) と定義
    Nonlinear:
      a: [0.0, 20.0]   # a: 論文で (0.0, 20.0) と定義
      kappa: [0.0, 5.0]  # kappa: 論文に制約なし。
      b1: [0.0, 5.0]   # b1: 論文に制約なし。
      b2: [-1.0, 0.0] # b2: 論文に制約なし。
    Kinetics:
      ka: [1e-6, 200.0] # ka: 論文で「正であること」と定義。図5D(23-131)を参考に上限を設定。
      kfi: [1e-6, 100.0] # kfi: 論文で「正であること」と定義。図5D(8-50)を参考に上限を設定。
      kfr: [1e-6, 100.0] # kfr: 論文で「正であること」と定義。図5D(1.4-87)を参考に上限を設定。
      ksi: [1e-6, 10.0] # ksi: 論文で「正であること」と定義。図5D(0.3-6)を参考に上限を設定。
      ksr: [1e-6, 1.0] # ksr: 論文で「正」かつ「1.0 s^-1 より遅い(小さい)」と定義。



# 差分化進化法の設定
optimization:
  maxiter: 1000
  popsize: 15
  updating: 'deferred'
  workers: -1

  # strategy を辞書に変更し、デフォルトを 'DE/rand/1/bin' (rand1bin) に設定
  strategy:
    # 'rand', 'best', 'randtobest', 'currenttobest' など
    mutation: 'rand'
    # 差分ベクトルの数 (通常 1 または 2)
    n_vectors: 1
    # 'bin' (binomial) または 'exp' (exponential)
    crossover: 'bin'