# config/config.yaml
defaults:

  - data: cb1 # デフォルトで使用するデータセット (cb1 or cb2)

  - _self_


# ハイパーパラメータの設定
hyper_params:

  # 刻み幅
  dt: 0.0002 # 1/5000 s
  #使用データのトリミング秒数
  trim_I_seconds: 2.0 # s
  trim_O_seconds: 1.0 # s

  # Linear Filterのパラメータ
  J: 15
  tau: 30


  # true: I2, ksi, ksr を最適化対象に含める
  # false: I2, ksi, ksr を強制的に 0.0 にする
  use_I2: true

  # パラメータの定義域
  param_bounds:
    LinearFilter:
      alphas: [-5.0, 5.0]  ## alphas (L1-L15): 論文に制約なし。
      delta: [0.0, 0.2] #  delta: 論文で (0.0, 0.002) 秒 (0-2ms) と定義、前任者のコードを参考に上限を 0.2 に設定。
    Nonlinear:
      a: [1e-6, 20.0]   # a: 論文で (0.0, 20.0) と定義
      kappa: [1e-6, 20.0]  # kappa: 論文に制約なし。erf関数との関係上普通負にはならないので下限を正の小さい値に設定。
      b1: [-10.0, 10.0]   # b1: 論文に制約なし。
      b2: [1e-6, 1.0] # b2: 論文に制約なし。負になると非現実的な応答になるため、下限を正の小さい値に設定。
    Kinetics:
      ka: [1e-6, 200.0] # ka: 論文で「正であること」と定義。図5D(23-131)を参考に上限を設定。
      kfi: [1e-6, 100.0] # kfi: 論文で「正であること」と定義。図5D(8-50)を参考に上限を設定。
      kfr: [1e-6, 100.0] # kfr: 論文で「正であること」と定義。図5D(1.4-87)を参考に上限を設定。
      ksi: [1e-6, 10.0] # ksi: 論文で「正であること」と定義。図5D(0.3-6)を参考に上限を設定。
      ksr: [1e-6, 1.0] # ksr: 論文で「正」かつ「1.0 s^-1 より遅い(小さい)」と定義。
    InitialStates:
      # (0.0, 1.0) の範囲で探索
      p_R: [0.0, 1.0]
      p_A: [0.0, 1.0]
      p_I1: [0.0, 1.0]
      p_I2: [0.0, 1.0] # use_I2: false の場合、(0.0, 0.0) に上書きされます



# 差分化進化法の設定
optimization:
  maxiter: 200 # 最大繰り返し回数
  popsize: 100 # 個体数 (探索候補の数)
  updating: 'deferred' # 並列計算の更新方法
  workers: -1 # 全てのCPUコアを使用

  # strategy を辞書に変更し、デフォルトを 'DE/rand/1/bin' (rand1bin) に設定
  strategy:
    # 'rand', 'best', 'randtobest', 'currenttobest' など
    mutation: 'rand'
    # 差分ベクトルの数 (通常 1 または 2)
    n_vectors: 1
    # 'bin' (binomial) または 'exp' (exponential)
    crossover: 'bin'