# config/config.yaml
defaults:

  - data: cb1 # デフォルトで使用するデータセット (cb1 or cb2)

  - _self_

segment: null # セグメント名 (null の場合、全データを使用, int 型でセグメントの秒数を指定)

# ハイパーパラメータの設定
hyper_params:

  # 刻み幅
  # データごとの dt を使用するため、/data/ 以下の YAML ファイルで指定
  # dt: 0.0002 # 1/5000 s

  # 選択肢: spearman, hybrid.
  objective_type: "hybrid"

  #使用データのトリミング秒数
  trim_I_seconds: 0.0 # s
  trim_O_seconds: 0.0 # s

  # Linear Filterのパラメータ
  # J: 15
  # カルシウム応答は約0.5〜1.0秒の履歴が必要なため、40〜60程度まで増やす、baccusはアレイを使ってたから早い
  J: 15

  # 大局（低周波）用の窓長（秒）
  tau: 1.0 # s 前任者より

  # 局所（高周波）用の短窓（秒）
  tau_short: 0.15 # s （例: 150ms）

  # true: I2, ksi, ksr を最適化対象に含める
  # false: I2, ksi, ksr を強制的に 0.0 にする
  use_I2: true

  # パラメータの定義域
  param_bounds:
    LinearFilter:
      alphas: [-10.0, 10.0]  ## alphas (L1-L15): 論文に制約なし。
      delta: [0.0, 1.0] #  delta: 論文で (0.0, 0.002) 秒 (0-2ms) と定義これはアレイ、カルシウム応答の遅れを許容するため上限を上げる
    Nonlinear:
      a: [1e-6, 10.0]   # a: 論文で (0.0, 20.0) と定義だが、過剰なゲイン抑制のため 10.0 に変更
      kappa: [1e-4, 2.0]  # kappa: 論文に制約なし。erf関数との関係上普通負にはならないので下限を正の小さい値に設定。
      b1: [-2.0, 2.0]   # b1: 論文に制約なし。、erf関数が飽和するため小さめに０を跨ぐように設定。erf関数は中身が2.0を超えるとほぼ1に飽和する。
      b2: [1e-6, 5.0] # b2: 論文に制約なし。負になると非現実的な応答になるため、下限を正の小さい値に設定。
    Kinetics:
      ka: [1e-6, 10.0] # ka: 論文で「正であること」と定義。ハイパス化抑制のため上限 50.0 -> 10.0 に変更
      kfi: [1e-6, 10.0] # kfi: 論文で「正であること」と定義。上限 50.0 -> 10.0 に変更
      kfr: [1e-6, 10.0] # kfr: 論文で「正であること」と定義。上限 100.0 -> 10.0 に変更
      ksi: [1e-6, 10.0] # ksi: 論文で「正であること」と定義。図5D(0.3-6)を参考に上限を設定。
      ksr: [1e-6, 1.0] # ksr: 論文で「正」かつ「1.0 s^-1 より遅い(小さい)」と定義。

    #InitialStates は定常状態計算により自動設定する
    # InitialStates:
    #   p_R: [0.0, 1.0]
    #   p_A: [0.0, 1.0]
    #   p_I1: [0.0, 1.0]
    #   p_I2: [0.0, 1.0] # use_I2: false の場合、(0.0, 0.0) に上書きされます

# 差分化進化法の設定
optimization:
  seed: 0 # main_limit.py の乱数シード
  maxiter: 1000 # 最大繰り返し回数
  popsize: 500 # 個体数 (探索候補の数)
  updating: 'deferred' # 並列計算の更新方法
  workers: -1 # 全てのCPUコアを使用

  # strategy を辞書に変更し、デフォルトを 'DE/rand/1/bin' (rand1bin) に設定
  strategy:
    # 'rand', 'best', 'randtobest', 'currenttobest' など
    mutation: 'rand'
    # 差分ベクトルの数 (通常 1 または 2)
    n_vectors: 1
    # 'bin' (binomial) または 'exp' (exponential)
    crossover: 'bin'
